name: Build and Deploy to Firebase hosting
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install npm dependecies
        run: npm install
      - name: Create Firebase config file
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo "export default $FIREBASE_CONFIG" > src/firebase.config.ts
      - name: Build project
        run: npm run build
      - name: Upload dist as artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: [build, deploy-functions, deploy-firestore, deploy-storage]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Download firebase-tools
        run: npm -g install firebase-tools
      - name: Download dist artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Setup Firebase project ID
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
        run: firebase use $FIREBASE_PROJECTID
      - name: Setup Firebase target
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_HOSTING_SITE: ${{ secrets.FIREBASE_HOSTING_SITE }}
        run: firebase target:apply hosting parsfood-admin $FIREBASE_HOSTING_SITE
      - name: Deploy to firebase hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting:parsfood-admin
  deploy-functions:
    name: Build and deploy Cloud Functions
    needs: [build, deploy-firestore, deploy-storage]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: functions/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Download firebase-tools
        run: npm -g install firebase-tools
      - name: Install npm dependecies
        run: npm --prefix functions install
      - name: Setup Firebase project ID
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
        run: firebase use $FIREBASE_PROJECTID
      - name: Deploy Cloud Functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only functions
  deploy-firestore:
    name: Deploy Cloud Firestore rules and indexes
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Download firebase-tools
        run: npm -g install firebase-tools
      - name: Setup Firebase project ID
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
        run: firebase use $FIREBASE_PROJECTID
      - name: Deploy Cloud Firestore rules and indexes
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only firestore
  deploy-storage:
    name: Deploy Cloud Storage rules
    needs: [build, deploy-firestore]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Download firebase-tools
        run: npm -g install firebase-tools
      - name: Setup Firebase project ID
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
        run: firebase use $FIREBASE_PROJECTID
      - name: Deploy Cloud Storage rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only storage
